#' Figure provenance records
#'
#' @name provenance
#' @keywords internal
NULL

# Build a structured provenance record for a workforce-density figure.
#
# Captures what the figure shows, how it was computed, and where the numerator
# and denominator came from, plus the generating call, package version, the
# date the source data were accessed, and a creation timestamp. Returned as a
# classed list ("mysterycall_provenance") so it can be attached to a figure via
# attr(p, "provenance"), printed, and written to a sidecar file.
.build_provenance <- function(metric,
                              computation,
                              numerator_desc,
                              denominator_desc,
                              generated_by,
                              per                = NA_real_,
                              years              = NULL,
                              n_series           = NA_integer_,
                              numerator_source   = NULL,
                              denominator_source = NULL,
                              denominator_vintage = NULL,
                              accessed           = NULL,
                              notes              = NULL) {
  pkg_version <- tryCatch(
    as.character(utils::packageVersion("mysterycall")),
    error = function(e) NA_character_
  )
  structure(
    list(
      metric          = metric,
      computation     = computation,
      numerator       = list(description = numerator_desc,
                             source      = numerator_source),
      denominator     = list(description = denominator_desc,
                             source      = denominator_source,
                             vintage     = denominator_vintage),
      per             = per,
      years           = if (is.null(years)) NULL else range(years),
      n_series        = n_series,
      generated_by    = generated_by,
      package_version = pkg_version,
      accessed        = if (is.null(accessed)) NA_character_ else as.character(accessed),
      created         = as.character(Sys.time()),
      notes           = if (is.null(notes)) NA_character_ else as.character(notes)
    ),
    class = "mysterycall_provenance"
  )
}

# A one-line source caption for the figure. Returns "" when no source is known.
.provenance_caption <- function(prov) {
  num <- prov$numerator$source   %||% prov$numerator$description
  den <- prov$denominator$source %||% prov$denominator$description
  parts <- character(0)
  if (!is.null(num) && !is.na(num) && nzchar(num))
    parts <- c(parts, paste0("Numerator: ", num))
  if (!is.null(den) && !is.na(den) && nzchar(den))
    parts <- c(parts, paste0("denominator: ", den))
  if (!length(parts)) return("")
  cap <- paste(parts, collapse = "; ")
  if (!is.na(prov$accessed) && nzchar(prov$accessed))
    cap <- paste0(cap, " (accessed ", prov$accessed, ")")
  paste0("Source — ", cap, ".")
}

# Human-readable multi-line provenance block, optionally with a per-point table
# and any number of named `extra` tables (each rendered as its own section).
.format_provenance <- function(prov, data = NULL, extra = NULL) {
  ln  <- function(label, value) {
    if (is.null(value) || (length(value) == 1L && is.na(value))) return(NULL)
    sprintf("%-15s %s", paste0(label, ":"), paste(value, collapse = ", "))
  }
  yr <- if (is.null(prov$years)) NULL else paste(prov$years, collapse = "–")
  head <- c(
    "mysterycall — figure provenance",
    strrep("=", 34),
    ln("Metric",        prov$metric),
    ln("Computation",   prov$computation),
    ln("Numerator",     prov$numerator$description),
    ln("  num. source", prov$numerator$source),
    ln("Denominator",   prov$denominator$description),
    ln("  den. source", prov$denominator$source),
    ln("  den. vintage",prov$denominator$vintage),
    ln("Scale (per)",   if (is.na(prov$per)) NULL else format(prov$per, scientific = FALSE)),
    ln("Years",         yr),
    ln("Series",        if (is.na(prov$n_series)) NULL else prov$n_series),
    ln("Generated by",  prov$generated_by),
    ln("Pkg version",   prov$package_version),
    ln("Data accessed", if (is.na(prov$accessed)) NULL else prov$accessed),
    ln("Created",       prov$created),
    ln("Notes",         if (is.na(prov$notes)) NULL else prov$notes)
  )
  block <- paste(head, collapse = "\n")

  if (!is.null(data) && is.data.frame(data) && nrow(data)) {
    tbl <- data
    num <- vapply(tbl, is.numeric, logical(1))
    tbl[num] <- lapply(tbl[num], function(v) ifelse(v == round(v), v, round(v, 4)))
    tbl_txt <- utils::capture.output(print(tbl, row.names = FALSE))
    block <- paste0(block, "\n\nPer-point values\n",
                    strrep("-", 16), "\n",
                    paste(tbl_txt, collapse = "\n"))
  }

  for (nm in names(extra)) {
    ex <- extra[[nm]]
    if (is.data.frame(ex) && nrow(ex)) {
      num <- vapply(ex, is.numeric, logical(1))
      ex[num] <- lapply(ex[num], function(v) ifelse(v == round(v), v, round(v, 4)))
      ex_txt <- utils::capture.output(print(ex, row.names = FALSE))
      title  <- gsub("_", " ", nm)
      block  <- paste0(block, "\n\n", title, "\n",
                       strrep("-", nchar(title)), "\n",
                       paste(ex_txt, collapse = "\n"))
    }
  }
  block
}

# Machine-readable payload for the JSON sidecar: the provenance record plus the
# per-point data table (and any named `extra` tables), wrapped with a schema tag.
.provenance_payload <- function(prov, data = NULL, extra = NULL) {
  payload <- list(
    schema         = "mysterycall/provenance",
    schema_version = "1",
    provenance     = unclass(prov)
  )
  if (!is.null(data) && is.data.frame(data) && nrow(data))
    payload$data <- data
  if (length(extra))
    payload[names(extra)] <- extra
  payload
}

# Write the provenance next to `output_path` (same basename): always a
# human-readable ".provenance.txt", and — when jsonlite is available — a
# machine-readable ".provenance.json". Returns the written paths invisibly.
.write_provenance <- function(prov, output_path, data = NULL, extra = NULL) {
  base  <- tools::file_path_sans_ext(output_path)
  txt   <- paste0(base, ".provenance.txt")
  writeLines(.format_provenance(prov, data, extra), txt)
  message("Provenance: ", txt)
  written <- txt

  if (requireNamespace("jsonlite", quietly = TRUE)) {
    json <- paste0(base, ".provenance.json")
    writeLines(
      jsonlite::toJSON(.provenance_payload(prov, data, extra),
                       auto_unbox = TRUE, pretty = TRUE, na = "null",
                       digits = NA),
      json
    )
    message("Provenance: ", json)
    written <- c(written, json)
  } else {
    message("Install 'jsonlite' to also emit a .provenance.json sidecar.")
  }
  invisible(written)
}

#' @export
print.mysterycall_provenance <- function(x, ...) {
  cat(.format_provenance(x), "\n")
  invisible(x)
}
